ros_gimbal_2D:
  joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 20

  tilt_joint_position_controller:
      type: position_controllers/JointPositionController
      joint: interceptor__interceptor__ros_gimbal_small_2d__tilt_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}
